{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rethinkdb.secretName" . }}
  labels:
    app.kubernetes.io/name: {{ template "rethinkdb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    helm.sh/chart: {{ template "rethinkdb.chart" . }}
type: Opaque
data:
  rethinkdb-password: {{ .Values.rethinkdbPassword | b64enc | quote }}
  {{- if .Values.proxy.driverTLS.enabled }}
  driver-key.pem: {{ .Values.proxy.driverTLS.key | b64enc | quote }}
  driver-cert.pem: {{ .Values.proxy.driverTLS.cert | b64enc| quote }}
  {{- end }}
{{- end }}