apiVersion: v1
kind: Service
metadata:
  name: "{{ template "rethinkdb.fullname" . }}-cluster"
  labels:
    app.kubernetes.io/name: "{{ template "rethinkdb.name" . }}-cluster"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    helm.sh/chart: {{ template "rethinkdb.chart" . }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  {{- if .Values.cluster.service.annotations }}
{{ toYaml .Values.cluster.service.annotations | indent 4 }}
  {{- end }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.ports.cluster }}
      targetPort: cluster
  selector:
    app.kubernetes.io/name: "{{ template "rethinkdb.name" . }}-cluster"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
