{{- if .Values.cluster.storageClass.enabled }}
apiVersion: {{ if .Capabilities.APIVersions.Has "storage.k8s.io/v1" -}}
  storage.k8s.io/v1
{{- else -}}
  storage.k8s.io/v1beta1
{{- end }}
kind: StorageClass
metadata:
  labels:
    app.kubernetes.io/name: "{{ template "rethinkdb.name" . }}-cluster"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    helm.sh/chart: {{ template "rethinkdb.chart" . }}
  name: {{ template "rethinkdb.fullname" . }}
provisioner: {{ .Values.cluster.storageClass.provisioner }}
parameters:
{{- range $key, $value := .Values.cluster.storageClass.parameters }}
  {{ $key }}: {{ $value }}
{{- end }}
{{- end }}
