apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ template "rethinkdb.fullname" . }}-proxy"
  labels:
    app.kubernetes.io/name: "{{ template "rethinkdb.name" . }}-proxy"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    helm.sh/chart: {{ template "rethinkdb.chart" . }}
spec:
  replicas: {{ .Values.proxy.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "rethinkdb.name" . }}-proxy
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
      app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
      helm.sh/chart: {{ template "rethinkdb.chart" . }}
  template:
    metadata:
      name: {{ template "rethinkdb.fullname" . }}-proxy
      labels:
        app.kubernetes.io/name: {{ template "rethinkdb.name" . }}-proxy
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        helm.sh/chart: {{ template "rethinkdb.chart" . }}
      annotations:
      {{- if .Values.proxy.podAnnotations }}
{{ toYaml .Values.proxy.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "rethinkdb.serviceAccountName" . }}
      containers:
        - name: {{ template "rethinkdb.name" . }}-proxy
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - name: cluster
              containerPort: {{ .Values.ports.cluster }}
            - name: driver
              containerPort: {{ .Values.ports.driver }}
            - name: admin
              containerPort: {{ .Values.ports.admin }}
          args:
            - "--bind"
            - "all"
            {{- if .Values.proxy.driverTLS.enabled }}
            - "--driver-tls-key"
            - "/secrets/driver-key.pem"
            - "--driver-tls-cert"
            - "/secrets/driver-cert.pem"
            {{- end }}
          volumeMounts:
            - name: "secrets"
              mountPath: "/secrets"
          livenessProbe:
{{ toYaml .Values.cluster.livenessProbe | indent 12 }}
          readinessProbe:
{{ toYaml .Values.cluster.readinessProbe | indent 12 }}
          env:
            - name: PROXY
              value: "true"
            - name: RETHINK_CLUSTER_SERVICE
              value: "{{ template "rethinkdb.fullname" . }}-cluster"
            - name: RETHINKDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "rethinkdb.secretName" . }}
                  key: rethinkdb-password
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
{{ toYaml .Values.proxy.resources | indent 12 }}
      volumes:
        - name: secrets
          projected:
            sources:
            - secret:
                name: {{ template "rethinkdb.secretName" . }}
